### ISSUE TITLE
What amount to reward NO Voters

### ISSUE THREAD

**Issue by hal909** [trusttoken/truefi-spec#5]
Currently we are awarding 2x the staked TRU on no votes, this might be too much and should take into account the remaining TRU distribution.

We also might want to have a penalty for voting no as well, so people don't always vote NO

**Comment by hal909** [comment]
proposal: 
Loan paid back: burn 10% TRU
Loan defaults: 2 * (TRU staked) * (remaining TRU distribution ratio)
this would scale better over time, since it's based on

**Comment by RafaelCosman** [comment]
**Simple way to do a prediction market:**
Regardless of what you predict, if you are wrong 100% of your TRU goes to the other side

**Slightly more complex:**
Regardless of what you predict, if you are wrong you lose 10% of your TRU.
Of whatever TRU are lost, 20% is burned and 80% is sent to the other side (you can think of this as the bookie's cut)

**Worked example of computing EV:**
$1mm loan for 6 months at 10% APR
This comes out to 5% total interest paid
EV = $50,000 * P(loan returned) + (-$1,000,000) * P(loan defaults)
      = $1,000,000 * ( 5% * P(loan returned) + (-1) * P(loan defaults) )

This is positive iff ( 5% * P(loan returned) + (-1) * P(loan defaults) ) is positive

which is positive iff      5% * P(loan returned) >  P(loan defaults)

Or more generally: APR * term in years * P(loan returned) >  P(loan defaults)

**Example for how to take risk into account: compute EV where _losses are twice as bad as gains are good_**

EV = $50,000 * P(loan returned) + (2 * -$1,000,000) * P(loan defaults)
      = $1,000,000 * ( 5% * P(loan returned) + (-2) * P(loan defaults) )

This is positive iff ( 5% * P(loan returned) + (-2) * P(loan defaults) ) is positive

which is positive iff      5% * P(loan returned) > 2 * P(loan defaults)

APR * term in years * P(loan returned) >  2 * P(loan defaults)

**Incentive distribution:**
Could just distribute for participating. No bias either way. 



**Why not make any loan with positive EV:**
1. We want to have some margin on the EV
2. More importantly: the pool should be risk averse

Minimum number of TRU participating in the prediction market: size of the loan in TUSD * factor
Factor will initially be set to 1

**You can think of this as a prediction market with conditional probabilities**
Regular prediction market: P(A) P(NOT A)
Conditional prediction market: P(loan returned | loan is made)  vs  P(loan defaults | loan is made)

**Comment by hal909** [comment]
Reward = (Amount of interest paid in TUSD) * (remaining TRU distribution)

Minimum votes = (size of loan in TUSD) * (factor)

- risk aversion:    how much worse is it to lose $1 than it is to gain $1
- participation:    how many TRU required to approve a loan
- lose factor:      25% of TRU lost if wrong
- burn factor:      25% lost TRU burned

Initial Values
lose factor:    0.25
burn factor:    0.25
participation:  1.00
risk aversion:  1.5

**Comment by hal909** [comment]
Prediction Market
- minimum number of TRU
- bet YES or NO
- winner gets a portion of the loser's TRU
- loser burns

Reward = (Amount of interest paid in TUSD) * (remaining TRU distribution for stakers)

Claimable reward = 
R * (current time / total time) * (account TRU staked / total TRU staked) - amount claimed

Minimum votes = (size of loan in TUSD) * (participation factor)

- risk aversion:    how much worse is it to lose $1 than it is to gain $1
- participation:    how many TRU required to approve a loan
- lose factor:      25% of TRU lost if wrong
- burn factor:      25% lost TRU burned

Initial Values
lose factor:    0.25
burn factor:    0.25
participation:  1.00
risk aversion:  1.5

v1 - bootstrapping lending protocol
v2 - automate, decentralize

stake 1000 TRU
lose -> 1000 * 0.25 = 250 TRU
burn -> 250 * 0.25 = 62.5 TRU burned
250 - 62.5 -> distributed to YES stakers

Risk aversion sets maximum % NO votes to approve loan

x = P(default)
f = 1.0
0 = 50,000(1-x) * f - 1,000,000(x)
0 = 50,000(1-x) * 1 - 1,000,000(x)
0 = 50,000(1-x) - 1,000,000(x)
1,000,000x = 50,000(1-x)
20x = 1-x
21x = 1
x = 1/21 = 0.04761904762
f == 2 ->  0.02380952381
f == 0.5-> 0.09523809524

% returned * P(loan returned) > P(loan defaults)
